/**
 * GENERATED by tools/gis/import_boundary.py — DO NOT EDIT BY HAND.
 *
 * Solio's authoritative reserve boundary (from the GIS File Geodatabase, layer
 * Boundary_Solio_Game_reserve). Ground-truth reserve edge in lng/lat.
 */

import { insidePolygon, pointToPathMeters, type LatLng } from "../lib/geo";

interface BoundaryPolygon {
  outer: LatLng[];
  holes: LatLng[][];
}

/** The reserve outline(s). Draw `RESERVE_BOUNDARY[i].outer` as a closed ring. */
export const RESERVE_BOUNDARY: BoundaryPolygon[] = [
  {
    outer: [
    { lng: 36.993799, lat: -0.153630 },
    { lng: 36.932300, lat: -0.200106 },
    { lng: 36.925375, lat: -0.226161 },
    { lng: 36.913874, lat: -0.240010 },
    { lng: 36.902412, lat: -0.241564 },
    { lng: 36.897228, lat: -0.250407 },
    { lng: 36.895628, lat: -0.252038 },
    { lng: 36.888429, lat: -0.253453 },
    { lng: 36.887168, lat: -0.244562 },
    { lng: 36.883383, lat: -0.241516 },
    { lng: 36.884060, lat: -0.237793 },
    { lng: 36.884860, lat: -0.230317 },
    { lng: 36.885506, lat: -0.227579 },
    { lng: 36.887115, lat: -0.218767 },
    { lng: 36.889110, lat: -0.190952 },
    { lng: 36.890988, lat: -0.165953 },
    { lng: 36.875730, lat: -0.159381 },
    { lng: 36.872092, lat: -0.149405 },
    { lng: 36.869015, lat: -0.147501 },
    { lng: 36.867676, lat: -0.144154 },
    { lng: 36.868425, lat: -0.140748 },
    { lng: 36.870020, lat: -0.137578 },
    { lng: 36.874627, lat: -0.137971 },
    { lng: 36.887991, lat: -0.139554 },
    { lng: 36.897653, lat: -0.140756 },
    { lng: 36.903065, lat: -0.141241 },
    { lng: 36.907566, lat: -0.140664 },
    { lng: 36.918901, lat: -0.141189 },
    { lng: 36.930198, lat: -0.141862 },
    { lng: 36.933083, lat: -0.139026 },
    { lng: 36.933416, lat: -0.138730 },
    { lng: 36.935738, lat: -0.139166 },
    { lng: 36.938101, lat: -0.139593 },
    { lng: 36.941409, lat: -0.140264 },
    { lng: 36.941816, lat: -0.140390 },
    { lng: 36.942107, lat: -0.141169 },
    { lng: 36.942860, lat: -0.140690 },
    { lng: 36.943805, lat: -0.140730 },
    { lng: 36.951347, lat: -0.140895 },
    { lng: 36.956948, lat: -0.140917 },
    { lng: 36.962078, lat: -0.141679 },
    { lng: 36.969068, lat: -0.142777 },
    { lng: 36.974176, lat: -0.143651 },
    { lng: 36.980942, lat: -0.144793 },
    { lng: 36.987417, lat: -0.149027 },
    { lng: 36.991382, lat: -0.151828 },
  ],
    holes: [],
  },
];

/** Default grace band (metres) around the fence — a guest at a gate, which sits
 * ON the boundary, still counts as inside, and absorbs GPS jitter at the edge. */
export const RESERVE_BUFFER_M = 150;

/**
 * True when a coordinate is inside the reserve. A point counts as inside a
 * polygon when it is within the outer ring and not within any hole.
 */
export function insideReserve(p: LatLng): boolean {
  return RESERVE_BOUNDARY.some(
    (poly) => insidePolygon(p, poly.outer) && !poly.holes.some((h) => insidePolygon(p, h)),
  );
}

/** Distance (m) from a point to the nearest boundary edge, ignoring side. */
export function distanceToBoundaryMeters(p: LatLng): number {
  return Math.min(
    ...RESERVE_BOUNDARY.map((poly) =>
      pointToPathMeters(p, [...poly.outer, poly.outer[0]]),
    ),
  );
}

/**
 * Inside the reserve, OR outside but within `bufferM` of the fence. Use this
 * (not raw `insideReserve`) for any "are they at Solio" test — gates sit on the
 * boundary, so an unbuffered test flags a guest at the gate as outside.
 */
export function insideReserveBuffered(p: LatLng, bufferM = RESERVE_BUFFER_M): boolean {
  return insideReserve(p) || distanceToBoundaryMeters(p) <= bufferM;
}

/** The outline as GeoJSON, for drawing the reserve edge on the map. */
export function boundaryGeoJSON(): GeoJSON.FeatureCollection {
  return {
    type: "FeatureCollection",
    features: RESERVE_BOUNDARY.map((poly) => ({
      type: "Feature" as const,
      properties: {},
      geometry: {
        type: "Polygon" as const,
        coordinates: [poly.outer, ...poly.holes].map((r) => [
          ...r.map((p) => [p.lng, p.lat]),
          [r[0].lng, r[0].lat],
        ]),
      },
    })),
  };
}
