# Exports blockers.permanent.geojson + blockers.open.geojson ->
# src/data/blockers.ts so the APP can refuse to imply a drive across a cut
# crossing (gpt-5.6-sol R8 finding 1 + R9 finding 1: the user->nearest-node
# connector was never policy-checked — a guest 10 m from S20, or at an OPEN
# permission-unknown site like S06, could "snap across" it and the drive
# distance would understate). Both sets ship: permanent cuts are policy, open
# cuts are unknowns — either way the connector must not jump them.
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
src = {"features": []}
for name in ("blockers.permanent.geojson", "blockers.open.geojson"):
    src["features"] += json.load(open(os.path.join(HERE, name)))["features"]
out = os.path.join(HERE, "..", "..", "src", "data", "blockers.ts")
lines = [
    "/**",
    " * GENERATED by tools/roads/export_blockers.py — DO NOT EDIT BY HAND.",
    " *",
    " * Cut crossing segments the road graph contains no edges across: the",
    " * PERMANENT cuts (S18/S20 Marriotts Private Road, agreed 2026-07-14) and",
    " * the OPEN permission-unknown sites (S05/S06/S16/S21/S22, awaiting",
    " * Callan). This export exists so RUNTIME",
    " * shortcuts (e.g. the user->nearest-node connector behind the popup's",
    " * approximate drive distance) can also refuse to jump them.",
    " */",
    "",
    'import type { LatLng } from "../lib/geo";',
    "",
    "/** Each entry is one cut crossing segment: [a, b]. */",
    "export const BLOCKER_SEGMENTS: [LatLng, LatLng][] = [",
]
for f in src["features"]:
    (x1, y1), (x2, y2) = f["geometry"]["coordinates"][0], f["geometry"]["coordinates"][-1]
    site = f["properties"]["site"]
    lines.append(f"  [{{ lng: {x1:.6f}, lat: {y1:.6f} }}, {{ lng: {x2:.6f}, lat: {y2:.6f} }}], // {site}")
lines += ["];", ""]
open(out, "w").write("\n".join(lines))
print(f"wrote {len(src['features'])} blocker segments -> {os.path.relpath(out, HERE)}")
