#!/usr/bin/env python3
"""Import Solio's authoritative reserve boundary into the app.

Reads the boundary layer as GeoJSON (EPSG:4326 lon,lat — export it from the
File Geodatabase with `tools/gis/export_layers.sh`) and emits
`src/data/boundary.ts`: the reserve outline as lng/lat rings plus an
`insideReserve()` point-in-polygon test. The boundary is Callan's ground-truth
reserve edge (47 vertices), so it is stored directly in world coordinates — no
round-trip through the poster georeference.

Usage:
    python3 tools/gis/import_boundary.py <boundary.geojson>
    python3 tools/gis/import_boundary.py <boundary.geojson> --out src/data/boundary.ts

No third-party dependencies; plain Python 3.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def load_polygons(path: Path) -> list[list[list[list[float]]]]:
    """Return a list of polygons; each polygon is [outer_ring, *hole_rings];
    each ring is a list of [lng, lat]."""
    data = json.loads(path.read_text())
    feats = data.get("features") if data.get("type") == "FeatureCollection" else [data]
    polys: list[list[list[list[float]]]] = []
    for f in feats:
        geom = (f.get("geometry") or {}) if f.get("type") == "Feature" else f
        t = geom.get("type")
        if t == "Polygon":
            polys.append(geom["coordinates"])
        elif t == "MultiPolygon":
            polys.extend(geom["coordinates"])
        else:
            print(f"  skipping geometry {t!r}")
    if not polys:
        sys.exit("error: no Polygon/MultiPolygon features found")
    return polys


def ring_ts(ring: list[list[float]]) -> str:
    # drop the closing duplicate vertex; insidePolygon closes the ring itself
    pts = ring[:-1] if len(ring) > 1 and ring[0] == ring[-1] else ring
    return "[\n" + "\n".join(
        f"    {{ lng: {c[0]:.6f}, lat: {c[1]:.6f} }}," for c in pts
    ) + "\n  ]"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("geojson", type=Path)
    ap.add_argument("--out", type=Path, default=ROOT / "src/data/boundary.ts")
    args = ap.parse_args()

    polys = load_polygons(args.geojson)
    nverts = sum(len(r) for poly in polys for r in poly)
    print(f"read {len(polys)} polygon(s), {nverts} vertices")

    poly_blocks = []
    for poly in polys:
        outer = ring_ts(poly[0])
        holes = ",\n    ".join(ring_ts(h) for h in poly[1:])
        poly_blocks.append(
            "  {\n"
            f"    outer: {outer},\n"
            f"    holes: [{holes}],\n"
            "  },"
        )
    polys_ts = "\n".join(poly_blocks)

    out = f'''/**
 * GENERATED by tools/gis/import_boundary.py — DO NOT EDIT BY HAND.
 *
 * Solio's authoritative reserve boundary (from the GIS File Geodatabase, layer
 * Boundary_Solio_Game_reserve). Ground-truth reserve edge in lng/lat.
 */

import {{ insidePolygon, pointToPathMeters, type LatLng }} from "../lib/geo";

interface BoundaryPolygon {{
  outer: LatLng[];
  holes: LatLng[][];
}}

/** The reserve outline(s). Draw `RESERVE_BOUNDARY[i].outer` as a closed ring. */
export const RESERVE_BOUNDARY: BoundaryPolygon[] = [
{polys_ts}
];

/** Default grace band (metres) around the fence — a guest at a gate, which sits
 * ON the boundary, still counts as inside, and absorbs GPS jitter at the edge. */
export const RESERVE_BUFFER_M = 150;

/**
 * True when a coordinate is inside the reserve. A point counts as inside a
 * polygon when it is within the outer ring and not within any hole.
 */
export function insideReserve(p: LatLng): boolean {{
  return RESERVE_BOUNDARY.some(
    (poly) => insidePolygon(p, poly.outer) && !poly.holes.some((h) => insidePolygon(p, h)),
  );
}}

/** Distance (m) from a point to the nearest boundary edge, ignoring side. */
export function distanceToBoundaryMeters(p: LatLng): number {{
  return Math.min(
    ...RESERVE_BOUNDARY.map((poly) =>
      pointToPathMeters(p, [...poly.outer, poly.outer[0]]),
    ),
  );
}}

/**
 * Inside the reserve, OR outside but within `bufferM` of the fence. Use this
 * (not raw `insideReserve`) for any "are they at Solio" test — gates sit on the
 * boundary, so an unbuffered test flags a guest at the gate as outside.
 */
export function insideReserveBuffered(p: LatLng, bufferM = RESERVE_BUFFER_M): boolean {{
  return insideReserve(p) || distanceToBoundaryMeters(p) <= bufferM;
}}

/** The outline as GeoJSON, for drawing the reserve edge on the map. */
export function boundaryGeoJSON(): GeoJSON.FeatureCollection {{
  return {{
    type: "FeatureCollection",
    features: RESERVE_BOUNDARY.map((poly) => ({{
      type: "Feature" as const,
      properties: {{}},
      geometry: {{
        type: "Polygon" as const,
        coordinates: [poly.outer, ...poly.holes].map((r) => [
          ...r.map((p) => [p.lng, p.lat]),
          [r[0].lng, r[0].lat],
        ]),
      }},
    }})),
  }};
}}
'''
    args.out.write_text(out)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
