/**
 * GENERATED by tools/roads/export_blockers.py — DO NOT EDIT BY HAND.
 *
 * Cut crossing segments the road graph contains no edges across: the
 * SETTLED cuts (S18/S20 Marriotts Private Road, agreed 2026-07-14; S06,
 * not a crossing — a toilet label, 2026-07-23) and the OPEN
 * permission-unknown sites (S05/S16/S21/S22, awaiting
 * Callan). This export exists so RUNTIME
 * shortcuts (e.g. the user->nearest-node connector behind the popup's
 * approximate drive distance) can also refuse to jump them.
 */

import type { LatLng } from "../lib/geo";

/** Each entry is one cut crossing segment: [a, b]. */
export const BLOCKER_SEGMENTS: [LatLng, LatLng][] = [
  [{ lng: 36.937133, lat: -0.158494 }, { lng: 36.936745, lat: -0.158460 }], // S06
  [{ lng: 36.897536, lat: -0.203856 }, { lng: 36.897560, lat: -0.203583 }], // S20
  [{ lng: 36.892313, lat: -0.202914 }, { lng: 36.892369, lat: -0.202644 }], // S18
  [{ lng: 36.898627, lat: -0.204042 }, { lng: 36.898521, lat: -0.203758 }], // S20
  [{ lng: 36.900252, lat: -0.203695 }, { lng: 36.900295, lat: -0.203577 }], // S20
  [{ lng: 36.899402, lat: -0.203743 }, { lng: 36.899130, lat: -0.203872 }], // S20
  [{ lng: 36.898524, lat: -0.203728 }, { lng: 36.898553, lat: -0.203395 }], // S20
  [{ lng: 36.899081, lat: -0.203319 }, { lng: 36.898556, lat: -0.203365 }], // S20
  [{ lng: 36.891601, lat: -0.203249 }, { lng: 36.892314, lat: -0.203280 }], // S18
  [{ lng: 36.891598, lat: -0.203279 }, { lng: 36.892273, lat: -0.203002 }], // S18
  [{ lng: 36.900177, lat: -0.204177 }, { lng: 36.900282, lat: -0.203728 }], // S20
  [{ lng: 36.898624, lat: -0.204072 }, { lng: 36.899098, lat: -0.203870 }], // S20
  [{ lng: 36.923047, lat: -0.197593 }, { lng: 36.923128, lat: -0.197417 }], // S16
  [{ lng: 36.910093, lat: -0.155046 }, { lng: 36.909870, lat: -0.154996 }], // S05
  [{ lng: 36.910115, lat: -0.155170 }, { lng: 36.910072, lat: -0.155288 }], // S05
  [{ lng: 36.898304, lat: -0.243575 }, { lng: 36.898317, lat: -0.243424 }], // S21
  [{ lng: 36.888202, lat: -0.250048 }, { lng: 36.888310, lat: -0.249935 }], // S22
  [{ lng: 36.909726, lat: -0.155898 }, { lng: 36.909801, lat: -0.155783 }], // S05
  [{ lng: 36.909656, lat: -0.155953 }, { lng: 36.909584, lat: -0.156039 }], // S05
  [{ lng: 36.887823, lat: -0.250290 }, { lng: 36.887756, lat: -0.250314 }], // S22
  [{ lng: 36.887721, lat: -0.250342 }, { lng: 36.888123, lat: -0.250590 }], // S22
  [{ lng: 36.909872, lat: -0.154966 }, { lng: 36.909871, lat: -0.155728 }], // S05
];
